### ISSUE TITLE
Legend for Icons?

### ISSUE THREAD

**Issue by ivysgagaronk** [cheesesashimi/theywhiteboardedme#1]
Love this site! 

Is there a spot somewhere that could include a legend for the icons, maybe in the FAQ? I can guess what the majority of them are but it might be nice to see so I know exactly what I am looking at. 

Thanks for putting this together!

**Comment by TETYYS** [comment]
there's this magical thing called "alt" attribute that explains the icons

**Comment by ivysgagaronk** [comment]
Oh totally! It's definitely easy enough to look at elements in Dev Tools and see what the alt attribute says (or just hover and wait for the description to pop up), but just from a UX perspective it might be nice to have a legend somewhere on the page.

**Comment by cheesesashimi** [comment]
Great idea, thanks :). These icons aren't the best so I admit I just put them there as placeholders until I could find something better.

**Comment by ivysgagaronk** [comment]
No worries at all! Thanks again for putting together such a great resource.

**Comment by cheesesashimi** [comment]
FYI: There is now a simple legend present on the list.
