### ISSUE TITLE
Argo AI

### ISSUE THREAD

**Issue by zackdouglas** [cheesesashimi/theywhiteboardedme#22]
# Company
[Argo AI](https://www.argo.ai/)

## Glassdoor
https://www.glassdoor.com/Overview/Working-at-Argo-AI-EI_IE1568279.11,18.htm

## Offenses:
 * [x] Online
 * [ ] Whiteboard
 * [x] Live
 * [ ] Homework

## Notes
"Online" and "Live" were taken during the same occasion.

**Comment by cheesesashimi** [comment]
Thanks for your contribution!
